// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace ASPNETCore5Sample.Models
{
    public partial class ContosoUniversityContext : DbContext
    {
        partial void OnModelCreatingPartial(ModelBuilder modelBuilder) 
        {
        }

        public override int SaveChanges()
        {
            var now = DateTime.Now;
            var entries = ChangeTracker
                .Entries()
                .Where(e => e.State == EntityState.Modified);

            foreach (var entityEntry in entries)
            {                
                if (entityEntry.Entity.GetType().GetProperty("DateModified") != null)
                {
                    entityEntry.Property("DateModified").CurrentValue = now;
                }
            }

            return base.SaveChanges();
        }
    }
}