// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace ASPNETCore5Sample.Models
{
    public partial class ContosoUniversityContext : DbContext
    {
        /// <summary>
        /// 取得單一DbSet
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <returns></returns>
        public DbSet<T> GetDbSet<T>() where T : class
        {
            return this.Set<T>();
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder)
        {
        }
    }
}